apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: development
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
hostPath:
  path: /mnt/data/dev
storageClassName: manual