apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    storage: 10Gi
storageClassName: manual