apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: prod-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-role-binding
  namespace: production
subjects:
- kind: Group
  name: production-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io
