apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: development
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "2"
    limits.memory: 4Gi
   
