groups:
- name: example-alerts
  rules:
  - alert: HighCpuUsage
    expr: avg(rate(container_cpu_usage_seconds_total[1m])) by (container) > 0.8
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for the last 5 minutes"
